# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-broker
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-broker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-broker
    spec:
      securityContext:
        runAsUser: {{ .Values.broker.uid }}
        runAsGroup: {{ .Values.broker.gid }}
      containers:
        - name: broker
          image: {{ .Values.broker.image }}:{{ .Values.broker.tag }}
          env:
            {{ include "proxy_envs" . | indent 12 }}
          ports:
            - containerPort: 1883
            - containerPort: 1884
          volumeMounts:
            - name: config-volume
              mountPath: /mosquitto/config
            - name: secrets-volume
              mountPath: /mosquitto/secrets/certs
          command: ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto-secure.conf"]
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-broker
            items:
              - key: mosquitto-secure.conf
                path: mosquitto-secure.conf
        - name: secrets-volume
          secret:
            secretName: {{ .Release.Name }}-certs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-broker
  namespace: {{ .Release.Namespace }}
data:
  mosquitto-secure.conf: |
{{ .Files.Get "files/mosquitto-secure.conf" | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  annotations: {{- toYaml .Values.mqttService.annotations | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-broker
  ports:
  - name: "1883"
    protocol: TCP
    port: 1883
    targetPort: 1883
  - name: "1884"
    protocol: TCP
    port: 1884
    targetPort: 1884
{{- if .Values.mqttService.nodePort.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: broker-np
  annotations: {{- toYaml .Values.mqttService.nodePort.annotations | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-broker
  ports:
  - name: "1883"
    protocol: TCP
    port: 1883
    targetPort: 1883
    nodePort: {{ .Values.mqttService.nodePort.nodePort }}
{{- end }}
{{- if .Values.mqttService.loadBalancer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: broker-lb
  annotations: {{- toYaml .Values.mqttService.loadBalancer.annotations | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-broker
  ports:
  - name: "1883"
    protocol: TCP
    port: 1883
    targetPort: 1883
  externalTrafficPolicy: {{ .Values.mqttService.loadBalancer.externalTrafficPolicy }}
  {{- if (default .Values.mqttService.loadBalancer.loadBalancerIP false) }}
  loadBalancerIP: {{ .Values.mqttService.loadBalancer.loadBalancerIP }}
  {{- end }}
{{- end }}
