# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pgserver-dep
  labels:
    app: {{ .Release.Name }}-pgserver
  annotations:
    container.apparmor.security.beta.kubernetes.io/pgserver: unconfined
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pgserver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pgserver
    spec:
      shareProcessNamespace: true
      containers:
        - name: {{ .Release.Name }}-pgserver
          image: {{ .Values.pgserver.repository }}/{{ .Values.pgserver.image }}:{{ .Values.pgserver.tag}}
          env:
            - name: POSTGRES_USER
              value: "scenescape"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db
                  key: DATABASE_PASSWORD
            - name: POSTGRES_DB
              value: "scenescape"
              {{ include "proxy_envs" . | indent 12 }}
          imagePullPolicy: Always
          securityContext:
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /workspace
              name: pgserver-storage
              subPath: workspace
            - mountPath: /workspace/media
              name: media-storage
{{- if .Values.tests.enabled }}
            - mountPath: /workspace/tests
              name: tests-storage
              subPath: tests
{{- end }}
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: dev-fuse
          hostPath:
            path: /dev/fuse
        - name: pgserver-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pgserver-pvc
        - name: media-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-media-pvc
{{- if .Values.tests.enabled }}
        - name: tests-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-tests-pvc
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: pgserver
spec:
  selector:
    app: {{ .Release.Name }}-pgserver
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
