# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

IMAGE = scenescape-percebro
RUNTIME_OS_IMAGE = ubuntu:22.04
FORCE_VAAPI ?= 0
TARGET = percebro-runtime

include ../common.mk

