# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.

IMAGE = scenescape-percebro
RUNTIME_OS_IMAGE = ubuntu:22.04
FORCE_VAAPI ?= 0

include ../common.mk
