# -*- mode: Fundamental; indent-tabs-mode: nil -*-

# SPDX-FileCopyrightText: (C) 2023 - 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:22.04

COPY Makefile common.mk version.txt /root/
COPY manager/config/user_access_config.json /root/docker/user_access_config.json
COPY manager/Makefile /root/manager/
COPY tools/certificates/ /root/tools/certificates/
COPY tools/authsecrets/Makefile /root/tools/authsecrets/

RUN apt-get update && apt-get install -y curl make python3 openssl \
    && curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x ./kubectl \
    && mv ./kubectl /usr/local/bin/kubectl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
