# -*- mode: Fundamental; indent-tabs-mode: nil -*-

# SPDX-FileCopyrightText: (C) 2023 - 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:22.04

COPY Makefile /root/Makefile
COPY manager/config/user_access_config.json /root/docker/user_access_config.json
COPY tools/certificates/Makefile /root/tools/certificates/Makefile
COPY tools/certificates/openssl.cnf /root/tools/certificates/openssl.cnf
COPY version.txt /root/sscape/version.txt

RUN apt-get update && apt-get install -y curl make python3

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl

CMD ["/bin/bash"]
