# -*- mode: Fundamental; indent-tabs-mode: nil -*-

# SPDX-FileCopyrightText: (C) 2023 - 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

FROM busybox

COPY models /root/models

COPY sample_data /root/sample_data
COPY controller/config/tracker-config.json /root/controller/tracker-config.json

CMD ["/bin/sh"]
