# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

add-orphaned-cameras: # NEX-T10402
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_add_orphaned_cameras.py, 'pgserver web scene', true, /run/secrets/controller.auth)

api-large-strings: # NEX-T10583
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_api_large_strings.py, 'pgserver web scene', true, /run/secrets/controller.auth)

auto-calibration:  # NEX-T10405
	$(call set-prefix)
	$(eval SERVICES := $(strip pgserver web queuing-video camcalibration))
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml:$(COMPOSE)/$(PREFIX)queuing_video.yml:$(COMPOSE)/camcalibration.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_auto_calibration.py, '$(SERVICES)', true, /run/secrets/browser.auth,tests/calibrationdb.tar.bz2)

child-scenes: # NEX-T10439
	$(call set-prefix)
	$(eval IMAGE_OLD := $(BASE_IMAGE))
	$(eval BASE_IMAGE := $(IMAGE)-controller-test)	
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_child_scenes.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval BASE_IMAGE := $(IMAGE_OLD))

delete-roi-mqtt: # NEX-T10430
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_delete_roi_mqtt.py, 'pgserver scene', true, /run/secrets/controller.auth)

delete-sensor-mqtt: # NEX-T10432
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_delete_sensor_mqtt.py, 'pgserver scene', true, /run/secrets/controller.auth)

delete-tripwire-mqtt: # NEX-T10431
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_delete_tripwire_mqtt.py, 'pgserver scene', true, /run/secrets/controller.auth)

geospatial-ingest-publish: # NEX-T10490
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_geospatial_ingest_publish.py, 'pgserver web scene', true, /run/secrets/controller.auth)

mqtt-auth: # NEX-T10423
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/security/system/negative_mqtt_insecure_auth.py)

mqtt-cert: # NEX-T10423
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/security/system/negative_mqtt_insecure_cert.py)

mqtt-roi: # NEX-T10404
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_roi_mqtt.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

mqtt-sensor-roi: # NEX-T10460
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_mqtt_sensor_roi.py, 'pgserver web scene', true, /run/secrets/controller.auth)

mqtt-slow-sensor-roi: # NEX-T10461
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_mqtt_slow_sensor_roi.py, 'pgserver web scene', true, /run/secrets/controller.auth)

mqtt-tripwire: # NEX-T10406
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_tripwire_mqtt.py, 'pgserver web scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

out-of-box: # NEX-T10417
	$(eval COMPOSE_FILES := $(if $(DLS),sample_data/docker-compose-dl-streamer-example.yml,sample_data/docker-compose-example.yml))
	$(eval SERVICES := $(strip pgserver web queuing-video retail-video scene))
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_out_of_box.py, '$(SERVICES)', true, /run/secrets/browser.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))


out-of-box-no-ntp: # NEX-T10417
	$(call set-prefix)
	$(eval SERVICES := $(strip pgserver web queuing-video retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/pgserver_default.yml:$(COMPOSE)/$(PREFIX)retail_video_no_ntp.yml:$(COMPOSE)/$(PREFIX)queuing_video_no_ntp.yml:$(COMPOSE)/scene_no_ntp.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_out_of_box.py, '$(SERVICES)', true, /run/secrets/browser.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

orphaned-sensor: # NEX-T10398
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_orphaned_sensor.py, 'pgserver web scene', true, /run/secrets/controller.auth)

percebro-3d-msgs: # NEX-T10507
	$(call common-recipe, $(COMPOSE)/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml:$(COMPOSE)/queuing_video_3d.yml, tests/functional/tc_check_3d_percebro_msgs.py, 'pgserver web scene queuing-video-3d', true, /run/secrets/controller.auth)

reid-performance-degradation: # NEX-T10541
	$(call set-prefix)
	$(eval IMAGE_OLD := $(BASE_IMAGE))
	$(eval BASE_IMAGE := $(IMAGE)-controller-test)
	$(eval SERVICES := $(strip pgserver web queuing-video retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver_default.yml:$(COMPOSE)/vdms.yml:$(COMPOSE)/$(PREFIX)retail_video_reid.yml:$(COMPOSE)/$(PREFIX)queuing_video_reid.yml:$(COMPOSE)/scene_reid.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_reid_performance_degradation.py, '$(SERVICES)', true)
	$(eval BASE_IMAGE := $(IMAGE_OLD))

reid-unique-count: # NEX-T10539
	$(call set-prefix)
	$(eval SERVICES := $(strip pgserver web queuing-video retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver_default.yml:$(COMPOSE)/vdms.yml:$(COMPOSE)/$(PREFIX)retail_video_reid.yml:$(COMPOSE)/$(PREFIX)queuing_video_reid.yml:$(COMPOSE)/scene_reid.yml:$(COMPOSE)/web.yml)
	$(eval BASE_IMAGE=$(IMAGE)-controller-test)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_reid_unique_count.py, '$(SERVICES)', true)
	$(eval BASE_IMAGE=$(IMAGE_OLD))

rest-test: # NEX-T10464
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_rest_test.py, 'pgserver web', true, /run/secrets/controller.auth)

sensors-send-events: # NEX-T10456
	$(call set-prefix)
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_sensors_send_mqtt_messages.py, 'pgserver web scene', true, /run/secrets/controller.auth)

vdms-similarity-search: # NEX-T10516
	$(eval IMAGE_OLD=$(BASE_IMAGE))
	$(eval BASE_IMAGE=$(IMAGE)-controller-test)
	$(call common-recipe, $(COMPOSE)/broker.yml:$(COMPOSE)/vdms.yml:$(COMPOSE)/pgserver_default.yml, tests/functional/tc_vdms_similarity_search.py,'pgserver',true, /run/secrets/controller.auth)
	$(eval BASE_IMAGE=$(IMAGE_OLD))

dlstreamer-api: # NEX-T12678
	$(call set-prefix)
	$(eval SERVICES := $(strip pgserver web queuing-video retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/$(PREFIX)broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/$(PREFIX)retail_video.yml:$(COMPOSE)/$(PREFIX)queuing_video.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/functional/tc_dlstreamer_api.py, '$(SERVICES)', true, /run/secrets/browser.auth)
