# SPDX-FileCopyrightText: (C) 2021 - 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.

EXTERNAL_MODELS_TESTS_PATH=tests/external_models
define external-models-recipe =
	$(eval TEST_SCRIPT=$1)
	$(eval PARAMS=$2)
	@if [ -z "${EXTERNAL_MODEL_PATH}" ] ; then echo EXTERNAL_MODEL_PATH must be set ; exit 1 ; fi
	$(eval LOGDIR=$(TEST_DATA)/external_models)
	$(eval LOGFILE=$(TEST_DATA)/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
	  ; echo RUNNING TEST $@ \
	  ; cd .. \
	  ; mkdir -p $(LOGDIR) \
	  ; env IMAGE=$(IMAGE):$(VERSION) ${TEST_SCRIPT} -z ${EXTERNAL_MODEL_PATH} -i sample_data/apriltag-cam1.mp4 ${PARAMS} 2>&1 | tee -i $(LOGFILE) \
	  ; echo "MAKE_TARGET: $@" | tee -ia $(LOGFILE) \
	  ; echo END TEST $@
endef

external-models-tests:\
  external-models-detection \
  external-models-system \
  external-models-threading \

# Recipes below must be in alphabetical order

external-models-detection: # NEX-T10514
	$(call external-models-recipe, $(EXTERNAL_MODELS_TESTS_PATH)/external_models_test_detection.py, -f 5.0)

external-models-system: # NEX-T10514
	@if [ -z "${EXTERNAL_MODEL_CATEGORIES}" ] ; then echo EXTERNAL_MODEL_CATEGORIES must be set ; exit 1 ; fi
	$(call external-models-recipe, $(EXTERNAL_MODELS_TESTS_PATH)/external_models_test_system.py, -c ${EXTERNAL_MODEL_CATEGORIES})

external-models-threading: # NEX-T10514
	$(call external-models-recipe, $(EXTERNAL_MODELS_TESTS_PATH)/external_models_test_threading.py, )
