# SPDX-FileCopyrightText: (C) 2021 - 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.

PERF_TESTS_PATH=tests/perf_tests
define perf-recipe =
	$(eval TEST_SCRIPT=$1)
	$(eval LOGFILE=$(TEST_DATA)/perf/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
	  ; echo RUNNING TEST $@ \
	  ; cd .. \
	  ; mkdir -p $(shell dirname $(LOGFILE)) \
	  ; env IMAGE=$(IMAGE):$(VERSION) BROWSER_IMAGE=$(IMAGE)-interface:$(VERSION) $(PERF_TESTS_PATH)/$(TEST_SCRIPT) 2>&1 | tee -i $(LOGFILE) \
	  ; echo "MAKE_TARGET: $@" | tee -ia $(LOGFILE) \
	  ; echo END TEST $@
endef

performance_tests:
	$(MAKE) -Otarget -j 1 _performance_tests SUPASS=$(SUPASS) -k

_performance_tests: \
  inference-conformance \
  inference-performance \
  inference-threading \
  scene-performance \
  default-models \
  quick-test-model \
  load-config-models \
  geometry-conformance \

geometry-conformance: \
  point-conformance \
  line-conformance \

# Recipes below must be in alphabetical order

default-models: # NEX-T10408
	$(call perf-recipe, tc_default_models.sh)

quick-test-model: # NEX-T10437
	$(call perf-recipe, tc_quick_test_model.sh)

load-config-models: # NEX-T10409
	$(call perf-recipe, tc_load_config_models.sh)

inference-conformance: # NEX-T10413
	$(call perf-recipe, tc_inference_conformance.sh)

inference-performance: # NEX-T10412
	$(call perf-recipe, tc_inference_performance.sh)

inference-threading: # NEX-T10421
	$(call perf-recipe, tc_inference_threading.sh)

scene-performance: # NEX-T10414
	$(call perf-recipe, tc_scene_performance.sh)

scene-performance-full: # NEX-T10488
	# 2 Cameras at 10fps, 2 models
	$(eval TARGET_RATE ?= 40)
	$(call perf-recipe, tc_scene_performance_full --target $(TARGET_RATE))

# Compare C++ geometry implementation
# vs original python implementation.
point-conformance:
	$(eval LOGDIR=$(TEST_DATA)/infra)
	$(eval LOGFILE=$(LOGDIR)/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
          ; echo RUNNING TEST $@ \
          ; cd .. \
          ; mkdir -p $(LOGDIR) \
          ; tools/scenescape-start $(PERF_TESTS_PATH)/tc_geometry_point.py | tee -ia $(LOGFILE) \
          ; echo END TEST $@

line-conformance:
	$(eval LOGDIR=$(TEST_DATA)/infra)
	$(eval LOGFILE=$(LOGDIR)/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
          ; echo RUNNING TEST $@ \
          ; cd .. \
          ; mkdir -p $(LOGDIR) \
          ; tools/scenescape-start $(PERF_TESTS_PATH)/tc_geometry_line.py | tee -ia $(LOGFILE) \
          ; echo END TEST $@
