#!/bin/bash

# SPDX-FileCopyrightText: (C) 2024 - 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.

# FIXME This example, make sure that '.scenescape' is added to the no_proxy environment
# variable

KUB_CLUSTER_FRP_ADDRESS=${KUB_CLUSTER_FRP_ADDRESS:-"host.docker.internal"}
KUB_CLUSTER_FRP_PORT=${KUB_CLUSTER_FRP_PORT:-"8080"}
KUB_CLUSTER_FRP_SECRET_KEY=${KUB_CLUSTER_FRP_SECRET_KEY:-"abcdefg"}
CERT_KUB_BROKER_URL=${CERT_KUB_BROKER_URL:-"broker.scenescape"}
CERT_KUB_WEB_URL=${CERT_KUB_WEB_URL:-"web.scenescape"}
PYTEST_KUB_WEB_URL="https://$CERT_KUB_WEB_URL"
PYTEST_KUB_REST_URL="$PYTEST_KUB_WEB_URL/api/v1"
