---
# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[CI] Update Image Caches"
run-name: "[CI] Update Image Caches"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1

permissions:
  contents: read

jobs:
  build-and-update:
    name: "Build SceneScape images and update caches"
    runs-on: [self-hosted]
    permissions:
      packages: write # For using GHCR as cache registry
    timeout-minutes: 60
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Remove all Docker images"
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Log in to GHCR"
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup Cache Targets"
        id: setup-cache
        uses: ./.github/actions/setup-cache

      - name: "Build Images and Update Caches"
        env:
          WRITE_CACHE: true
          CACHE_REGISTRY: ${{ steps.setup-cache.outputs.cache_registry }}
          GHCR_CACHE: ${{ steps.setup-cache.outputs.ghcr_cache }}
        run: |
          make build-all
