---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[CI] Clean self-hosted runner"
run-name: "[CI] Clean self-hosted runner"

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  clean-runner:
    name: "Clean self-hosted runner"
    runs-on: [to-be-cleaned]
    steps:
      - name: "Clean workdir before checkout"
        run: |
          sudo rm -rf $GITHUB_WORKSPACE/* || true
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"
