---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[CI/CD] Publish Docs"
run-name: "[CI/CD] Publish Docs"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      switch_main_to_dev:
        description: >-
          When true, replaces 'main' branch with 'dev' in version switcher
        required: false
        default: true
        type: boolean

permissions:
  contents: read # needed for actions/checkout
  pull-requests: read # needed for gh pr list
  issues: write # needed to post PR comment

jobs:
  build_toplevel:
    name: "Build Toplevel Documentation"
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@e2d6d9a8c38f021fcef3e3094f930486146a4612
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      switch_main_to_dev: ${{ github.event.inputs.switch_main_to_dev }}

  build_autocalibration:
    name: "Build Autocalibration Documentation"
    needs: [build_toplevel]
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@e2d6d9a8c38f021fcef3e3094f930486146a4612
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: autocalibration
      switch_main_to_dev: ${{ github.event.inputs.switch_main_to_dev }}

  build_controller:
    name: "Build Controller Documentation"
    needs: [build_toplevel]
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@e2d6d9a8c38f021fcef3e3094f930486146a4612
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: controller
      switch_main_to_dev: ${{ github.event.inputs.switch_main_to_dev }}
